### ISSUE TITLE
template fhs-simple needs an update

### ISSUE THREAD

**Issue by frase-git** [cmsimple-xh/cmsimple-xh#274]
replace in `stylesheet.css` the lines 35 - 44 with following lines:
```css
b, strong {
	font-family: "OpenSans-Semibold", sans-serif;
	font-style: normal;
	font-weight: normal;
}
b i, strong i, b em, strong em, i b, i strong, em b, em strong {
	font-family: "OpenSans-SemiboldItalic", sans-serif;
	font-style: normal;
	font-weight: normal;
}
```
